### ISSUE TITLE
Unknown field "approval_prompt"

### ISSUE THREAD

**Issue by jamesfairhurst** [pixelfear/oauth2-dropbox#5]
Hello,

Seems like this has been an error in the past but was solved, however I'm now getting it. Using "league/oauth2-client": "~1.0" which seems to always pass the approval_prompt in the Auth URL. Do you need to uncomment your override again?

Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.

More details for developers

unknown field "approval_prompt"

**Comment by jamesfairhurst** [comment]
OK so looks like you can override that when generating the Auth URL by using an empty array:

```$authUrl = $provider->getAuthorizationUrl(['approval_prompt' => []]);```

Bit messy so personally I would re-instate your commented out ```getAuthorizationUrl``` method so the readme example works out of the box (or update the example)

**Comment by jamesfairhurst** [comment]
Also included in PR, please see comments there.

**Comment by richardhj** [comment]
+1
