### ISSUE TITLE
Invalid getResourceOwnerDetailsUrl() method

### ISSUE THREAD

**Issue by jamesfairhurst** [pixelfear/oauth2-dropbox#6]
Getting the following error due to the tacked on access_token in the URL. This has [apparently changed](https://www.dropbox.com/developers-v1/core/docs#account-info) looking at their docs.

```Cannot specify both an "Authorization" header and the URL/POST parameter "access_token".```

Looking into a PR now.

**Comment by jamesfairhurst** [comment]
Not sure how I closed this. Feel free todo so after the PR review. Thanks!

**Comment by richardhj** [comment]
+1
